### ISSUE TITLE
How to use custom subdomain

### ISSUE THREAD

**Issue by androidacy-user** [fingerprintjs/fingerprintjs-pro-android-integrations#31]
When trying to use the following:

```java
Configuration configuration = new Configuration(
    "api-key",
   Configuration.Region.US,
   "https://our.sub.domain",
   true
);
```

The application crashes with:
```java
E/AndroidRuntime: FATAL EXCEPTION: pool-151-thread-1
    Process: com.our.app, PID: 18991
    java.lang.NullPointerException
        at com.fingerprintjs.android.fingerprint.FingerprinterFactory.getInstance(FingerprinterFactory.kt:83)
        at fpproc.j.a(SourceFile:1)
        at fpproc.j$$ExternalSyntheticLambda0.run(Unknown Source:10)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

Earlier logs show the following:
```java
E/FingerprintJS: fpproc.j: Error: Network error. Check your connection or the endpoint URL Request ID: Unknown
```

Said subdomain works fine with the javascript client i might note

**Comment by Alexey-Verkhovsky** [comment]
Hello! 
What's the version of the library you are using? 

Make sure you have integrated:
```groovy
  implementation "com.fingerprint.android:pro:2.2.1"
  implementation "com.github.fingerprintjs:fingerprint-android:2.0.0"
```
from: 
```repositories {
  ...
  maven { url 'https://maven.fpregistry.io/releases' }	
  maven { url 'https://jitpack.io' }	

}```

**Comment by Alexey-Verkhovsky** [comment]
We checked everything on our end and didn't find any troubles, all mobile libraries work fine with subdomain integration.

Do you use the same subdomain for web and for mobile? 
In the dashboard, have you completed all the steps for subdomain integration, and you see no "Pending" or "Validation" messages?
What if you place the IP address instead of your subdomain – is it working, or you still have the network error?

**Comment by Alexey-Verkhovsky** [comment]
Sorry for me asking some silly questions, but out of the context you provided we don't see any issues. Other customers haven't met problems with subdomain integration on Mobile, so we assumed there was some sort of misconfiguration / DNS issues. That's why we asked you that. 

Sorry again for not meeting your expectations, we're wishing you luck!
